"""Add FolderCategories table

Revision ID: 51baa70aeef2
Revises: febde6303216
Create Date: 2025-11-05 12:33:30.786312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51baa70aeef2'
down_revision: Union[str, Sequence[str], None] = 'febde6303216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only create folder_categories table - users, session, and email_processing_queue already exist from previous migrations
    op.create_table('folder_categories',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('gmail_label_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_folder_name')
    )
    op.create_index('ix_folder_categories_gmail_label_id', 'folder_categories', ['gmail_label_id'], unique=False)
    op.create_index('ix_folder_categories_user_id', 'folder_categories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop folder_categories table
    op.drop_index('ix_folder_categories_user_id', table_name='folder_categories')
    op.drop_index('ix_folder_categories_gmail_label_id', table_name='folder_categories')
    op.drop_table('folder_categories')
    # ### end Alembic commands ###
