"""Add EmailProcessingQueue table

Revision ID: febde6303216
Revises: 7ac211a986e7
Create Date: 2025-11-05 11:44:39.257763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'febde6303216'
down_revision: Union[str, Sequence[str], None] = '7ac211a986e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_processing_queue',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('proposed_folder_id', sa.Integer(), nullable=True),
    sa.Column('draft_response', sa.Text(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    op.create_index('ix_email_processing_queue_gmail_message_id', 'email_processing_queue', ['gmail_message_id'], unique=False)
    op.create_index('ix_email_processing_queue_gmail_thread_id', 'email_processing_queue', ['gmail_thread_id'], unique=False)
    op.create_index('ix_email_processing_queue_status', 'email_processing_queue', ['status'], unique=False)
    op.create_index('ix_email_processing_queue_user_id', 'email_processing_queue', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_processing_queue_user_id', table_name='email_processing_queue')
    op.drop_index('ix_email_processing_queue_status', table_name='email_processing_queue')
    op.drop_index('ix_email_processing_queue_gmail_thread_id', table_name='email_processing_queue')
    op.drop_index('ix_email_processing_queue_gmail_message_id', table_name='email_processing_queue')
    op.drop_table('email_processing_queue')
    # ### end Alembic commands ###
