#!/bin/bash
#
# Interactive GitHub Secrets Setup Wizard
# Guides you through creating all necessary secrets
#

set -e

SECRETS_FILE=".env.secrets"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

print_header() {
    echo ""
    echo -e "${BLUE}================================================${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}================================================${NC}"
    echo ""
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

ask_value() {
    local prompt=$1
    local default=$2
    local value

    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " value
        echo "${value:-$default}"
    else
        read -p "$prompt: " value
        echo "$value"
    fi
}

ask_multiline() {
    local prompt=$1
    echo "$prompt"
    echo "(Paste content, then press Ctrl+D on a new line)"
    cat
}

clear
print_header "Mail Agent - GitHub Secrets Setup Wizard"

echo "This wizard will help you create all necessary GitHub Secrets."
echo "You'll need information from:"
echo "  - Oracle Cloud Console"
echo "  - Google Cloud Console (for Gmail OAuth)"
echo "  - Google AI Studio (for Gemini)"
echo "  - Groq Console"
echo ""
read -p "Press Enter to continue..."

# Step 1: Generate auto-secrets
print_header "Step 1: Generating Random Secrets"

JWT_SECRET=$(openssl rand -base64 32)
ENCRYPTION_KEY=$(openssl rand -base64 32)

print_success "JWT_SECRET_KEY generated"
print_success "ENCRYPTION_KEY generated"

# Step 2: Oracle Cloud VMs
print_header "Step 2: Oracle Cloud VM IP Addresses"

print_info "Get these from: Oracle Console → Compute → Instances"
echo ""

STAGING_VM_IP=$(ask_value "Staging VM Public IP")
PRODUCTION_VM_IP=$(ask_value "Production VM Public IP")

# Step 3: SSH Key
print_header "Step 3: SSH Private Key"

print_info "Paste your SSH private key (from ~/.ssh/oracle_key)"
print_warning "Include the BEGIN and END lines!"
echo ""
ORACLE_SSH_PRIVATE_KEY=$(ask_multiline "SSH Private Key:")

# Step 4: Database URLs
print_header "Step 4: Database Connection Strings"

print_info "Get these from: Oracle Console → Autonomous Database → DB Connection"
print_info "Format: postgresql://admin:password@host:1522/database_name"
echo ""

STAGING_DATABASE_URL=$(ask_value "Staging Database URL")
PRODUCTION_DATABASE_URL=$(ask_value "Production Database URL")

# Step 5: Gmail OAuth
print_header "Step 5: Gmail OAuth Credentials"

print_info "Get these from: https://console.cloud.google.com"
print_info "APIs & Services → Credentials → OAuth 2.0 Client ID"
echo ""

GMAIL_CLIENT_ID=$(ask_value "Gmail Client ID")
GMAIL_CLIENT_SECRET=$(ask_value "Gmail Client Secret")

# Step 6: AI API Keys
print_header "Step 6: AI API Keys"

print_info "Gemini: https://aistudio.google.com/app/apikey"
print_info "Groq: https://console.groq.com"
echo ""

GEMINI_API_KEY=$(ask_value "Gemini API Key")
GROQ_API_KEY=$(ask_value "Groq API Key")

# Step 7: Frontend URLs
print_header "Step 7: API URLs"

STAGING_API_URL="http://${STAGING_VM_IP}:8000"
PRODUCTION_API_URL="http://${PRODUCTION_VM_IP}:8000"

echo "Staging API URL: $STAGING_API_URL"
echo "Production API URL: $PRODUCTION_API_URL"
echo ""
read -p "Use these URLs? (y/n): " use_default_urls

if [ "$use_default_urls" != "y" ]; then
    STAGING_API_URL=$(ask_value "Staging API URL" "$STAGING_API_URL")
    PRODUCTION_API_URL=$(ask_value "Production API URL" "$PRODUCTION_API_URL")
fi

# Create secrets file
print_header "Saving Secrets"

cat > "$SECRETS_FILE" << EOF
# Mail Agent - GitHub Secrets
# Generated by setup wizard at: $(date)
#
# ⚠️  DO NOT COMMIT THIS FILE!

# Auto-generated
JWT_SECRET_KEY=$JWT_SECRET
ENCRYPTION_KEY=$ENCRYPTION_KEY

# Oracle Cloud
STAGING_VM_IP=$STAGING_VM_IP
PRODUCTION_VM_IP=$PRODUCTION_VM_IP
ORACLE_SSH_PRIVATE_KEY=$ORACLE_SSH_PRIVATE_KEY

# Databases
STAGING_DATABASE_URL=$STAGING_DATABASE_URL
PRODUCTION_DATABASE_URL=$PRODUCTION_DATABASE_URL

# Gmail OAuth
GMAIL_CLIENT_ID=$GMAIL_CLIENT_ID
GMAIL_CLIENT_SECRET=$GMAIL_CLIENT_SECRET

# AI APIs
GEMINI_API_KEY=$GEMINI_API_KEY
GROQ_API_KEY=$GROQ_API_KEY

# Frontend URLs
STAGING_API_URL=$STAGING_API_URL
PRODUCTION_API_URL=$PRODUCTION_API_URL
EOF

print_success "Secrets saved to: $SECRETS_FILE"

# Add to .gitignore
if ! grep -q ".env.secrets" .gitignore 2>/dev/null; then
    echo ".env.secrets" >> .gitignore
    print_success "Added to .gitignore"
fi

# Upload to GitHub
print_header "Upload to GitHub?"

echo "Do you want to upload these secrets to GitHub now?"
echo ""
read -p "Upload to GitHub? (y/n): " upload_now

if [ "$upload_now" = "y" ]; then
    # Check if gh is installed
    if ! command -v gh &> /dev/null; then
        print_error "GitHub CLI (gh) not installed!"
        echo ""
        echo "Install it first:"
        echo "  macOS: brew install gh"
        echo ""
        echo "Then run:"
        echo "  bash scripts/upload-secrets.sh"
    else
        bash scripts/upload-secrets.sh
    fi
else
    echo ""
    print_info "Secrets saved to $SECRETS_FILE"
    echo ""
    echo "To upload later, run:"
    echo "  bash scripts/upload-secrets.sh"
fi

print_header "Setup Complete!"

print_success "All secrets configured!"
echo ""
echo "Next steps:"
echo "  1. Verify secrets on GitHub:"
echo "     https://github.com/1987-Dmytro/Mail-Agent/settings/secrets/actions"
echo ""
echo "  2. Delete the secrets file (after upload):"
echo "     rm $SECRETS_FILE"
echo ""
echo "  3. Start deployment:"
echo "     git add . && git commit -m 'ci: Add CI/CD infrastructure'"
echo "     git push origin develop"
echo ""
